# =========================
# DATABASE (SUPABASE POSTGRES)
# =========================
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =========================
# SERVER (RENDER)
# =========================
server.port=${PORT:8080}
server.servlet.context-path=/api

# =========================
# HIKARI (PROD SAFE)
# =========================
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.data-source-properties.prepareThreshold=0

# =========================
# JPA (PROD)
# =========================
spring.jpa.show-sql=false
spring.jpa.defer-datasource-initialization=false

# =========================
# LOGGING (PROD CLEAN)
# =========================
logging.level.root=WARN
logging.level.org.springframework.boot=INFO
logging.level.org.hibernate=ERROR
logging.level.com.zaxxer.hikari=WARN

# =========================
# ACTUATOR (PROD SAFE)
# =========================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# =========================
# CORS (FRONT PROD)
# =========================
app.cors.allowed-origins=https://feeltrack-frontend.vercel.app/

# =========================
# EXTERNAL API
# =========================
huggingface.token=${HUGGINGFACE_TOKEN}