# =========================
# DATABASE (LOCAL MARIADB)
# =========================
spring.datasource.url=jdbc:mariadb://localhost:3307/sa
spring.datasource.name=${DB_NAME:sa}
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# HikariCP - fail fast (dev only)
spring.datasource.hikari.initialization-fail-timeout=1
spring.datasource.hikari.connection-timeout=2000
spring.datasource.hikari.validation-timeout=1000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

# =========================================================
# JPA / HIBERNATE
# =========================================================
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# =========================
# LOGGING (DEV - VERBOSE)
# =========================
logging.level.root=INFO

logging.level.org.springframework.boot=INFO
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.springframework.orm.jpa=DEBUG

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.com.zaxxer.hikari=INFO

logging.level.ld.feeltrack_backend=DEBUG

spring.output.ansi.enabled=ALWAYS

# =========================
# CORS (LOCAL FRONT)
# =========================
app.cors.allowed-origins=http://localhost:**

# =========================
# ACTUATOR (DEV)
# =========================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# =========================
# EXTERNAL API
# =========================
huggingface.token=${HUGGINGFACE_TOKEN}