spring.application.name=feeltrack-backend

# Disables automatic naming strategy conversions from Spring Boot/Hibernate
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Global API base path prefix
server.servlet.context-path=/api